title: aaoth

plugins:
  - jekyll-feed

# exclude non-site files
exclude:
  - LICENSE
  - README.md
  - art/thumbs.sh

collections:
  music_releases:

  music_projects:
    output: true
    permalink: /music/:title
    sort_by: start_date

excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: "_posts"
    values:
      layout: "post"

  - scope:
      path: "_music_projects"
    values:
      layout: "music-project"

  - scope:
      path: "assets/img"
    values:
      image: true

  - scope:
      path: "art"
    values:
      art: true

  - scope:
      path: "art/*/thumbs"
    values:
      thumbnail: true
