title: aaoth

plugins:
  - jekyll-feed

# exclude non-site files
exclude:
  - LICENSE
  - README.md
  - art/thumbs.sh
  - aaoth_new_post.sh
  - post-receive.example
  - templates

# sadly wildcards don't work
keep_files:
  - visual/photos/thumbs
  - visual/renders/thumbs
  - visual/drawings/thumbs
  - visual/logos/thumbs

collections:
  music_releases:
    output: true

  music_projects:
    output: true
    permalink: /music/:title/
    sort_by: start_date

  music_titles:

excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: "_posts"
    values:
      layout: "post"

  - scope:
      type: "music_projects"
    values:
      layout: "music-project"

  - scope:
      path: ""
      type: "music_releases"
    values:
      layout: "music-release"

  - scope:
      path: "assets/img"
    values:
      image: true

  - scope:
      path: "visual"
    values:
      art: true

  - scope:
      path: "visual/*/thumbs"
    values:
      thumbnail: true
